// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="DataMatrixVersion.cs">
//   Copyright (c) 2023 Aspose.BarCode for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Aspose.BarCode.Cloud.Sdk.Model
{

    /// <summary>
    ///
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataMatrixVersion
    {
        /// <summary>
        ///     Enum value Auto
        /// </summary>
        Auto,

        /// <summary>
        ///     Enum value RowsColumns
        /// </summary>
        RowsColumns,

        /// <summary>
        ///     Enum value ECC000_9x9
        /// </summary>
        ECC000_9x9,

        /// <summary>
        ///     Enum value ECC000_050_11x11
        /// </summary>
        ECC000_050_11x11,

        /// <summary>
        ///     Enum value ECC000_100_13x13
        /// </summary>
        ECC000_100_13x13,

        /// <summary>
        ///     Enum value ECC000_100_15x15
        /// </summary>
        ECC000_100_15x15,

        /// <summary>
        ///     Enum value ECC000_140_17x17
        /// </summary>
        ECC000_140_17x17,

        /// <summary>
        ///     Enum value ECC000_140_19x19
        /// </summary>
        ECC000_140_19x19,

        /// <summary>
        ///     Enum value ECC000_140_21x21
        /// </summary>
        ECC000_140_21x21,

        /// <summary>
        ///     Enum value ECC000_140_23x23
        /// </summary>
        ECC000_140_23x23,

        /// <summary>
        ///     Enum value ECC000_140_25x25
        /// </summary>
        ECC000_140_25x25,

        /// <summary>
        ///     Enum value ECC000_140_27x27
        /// </summary>
        ECC000_140_27x27,

        /// <summary>
        ///     Enum value ECC000_140_29x29
        /// </summary>
        ECC000_140_29x29,

        /// <summary>
        ///     Enum value ECC000_140_31x31
        /// </summary>
        ECC000_140_31x31,

        /// <summary>
        ///     Enum value ECC000_140_33x33
        /// </summary>
        ECC000_140_33x33,

        /// <summary>
        ///     Enum value ECC000_140_35x35
        /// </summary>
        ECC000_140_35x35,

        /// <summary>
        ///     Enum value ECC000_140_37x37
        /// </summary>
        ECC000_140_37x37,

        /// <summary>
        ///     Enum value ECC000_140_39x39
        /// </summary>
        ECC000_140_39x39,

        /// <summary>
        ///     Enum value ECC000_140_41x41
        /// </summary>
        ECC000_140_41x41,

        /// <summary>
        ///     Enum value ECC000_140_43x43
        /// </summary>
        ECC000_140_43x43,

        /// <summary>
        ///     Enum value ECC000_140_45x45
        /// </summary>
        ECC000_140_45x45,

        /// <summary>
        ///     Enum value ECC000_140_47x47
        /// </summary>
        ECC000_140_47x47,

        /// <summary>
        ///     Enum value ECC000_140_49x49
        /// </summary>
        ECC000_140_49x49,

        /// <summary>
        ///     Enum value ECC200_10x10
        /// </summary>
        ECC200_10x10,

        /// <summary>
        ///     Enum value ECC200_12x12
        /// </summary>
        ECC200_12x12,

        /// <summary>
        ///     Enum value ECC200_14x14
        /// </summary>
        ECC200_14x14,

        /// <summary>
        ///     Enum value ECC200_16x16
        /// </summary>
        ECC200_16x16,

        /// <summary>
        ///     Enum value ECC200_18x18
        /// </summary>
        ECC200_18x18,

        /// <summary>
        ///     Enum value ECC200_20x20
        /// </summary>
        ECC200_20x20,

        /// <summary>
        ///     Enum value ECC200_22x22
        /// </summary>
        ECC200_22x22,

        /// <summary>
        ///     Enum value ECC200_24x24
        /// </summary>
        ECC200_24x24,

        /// <summary>
        ///     Enum value ECC200_26x26
        /// </summary>
        ECC200_26x26,

        /// <summary>
        ///     Enum value ECC200_32x32
        /// </summary>
        ECC200_32x32,

        /// <summary>
        ///     Enum value ECC200_36x36
        /// </summary>
        ECC200_36x36,

        /// <summary>
        ///     Enum value ECC200_40x40
        /// </summary>
        ECC200_40x40,

        /// <summary>
        ///     Enum value ECC200_44x44
        /// </summary>
        ECC200_44x44,

        /// <summary>
        ///     Enum value ECC200_48x48
        /// </summary>
        ECC200_48x48,

        /// <summary>
        ///     Enum value ECC200_52x52
        /// </summary>
        ECC200_52x52,

        /// <summary>
        ///     Enum value ECC200_64x64
        /// </summary>
        ECC200_64x64,

        /// <summary>
        ///     Enum value ECC200_72x72
        /// </summary>
        ECC200_72x72,

        /// <summary>
        ///     Enum value ECC200_80x80
        /// </summary>
        ECC200_80x80,

        /// <summary>
        ///     Enum value ECC200_88x88
        /// </summary>
        ECC200_88x88,

        /// <summary>
        ///     Enum value ECC200_96x96
        /// </summary>
        ECC200_96x96,

        /// <summary>
        ///     Enum value ECC200_104x104
        /// </summary>
        ECC200_104x104,

        /// <summary>
        ///     Enum value ECC200_120x120
        /// </summary>
        ECC200_120x120,

        /// <summary>
        ///     Enum value ECC200_132x132
        /// </summary>
        ECC200_132x132,

        /// <summary>
        ///     Enum value ECC200_144x144
        /// </summary>
        ECC200_144x144,

        /// <summary>
        ///     Enum value ECC200_8x18
        /// </summary>
        ECC200_8x18,

        /// <summary>
        ///     Enum value ECC200_8x32
        /// </summary>
        ECC200_8x32,

        /// <summary>
        ///     Enum value ECC200_12x26
        /// </summary>
        ECC200_12x26,

        /// <summary>
        ///     Enum value ECC200_12x36
        /// </summary>
        ECC200_12x36,

        /// <summary>
        ///     Enum value ECC200_16x36
        /// </summary>
        ECC200_16x36,

        /// <summary>
        ///     Enum value ECC200_16x48
        /// </summary>
        ECC200_16x48,

        /// <summary>
        ///     Enum value DMRE_8x48
        /// </summary>
        DMRE_8x48,

        /// <summary>
        ///     Enum value DMRE_8x64
        /// </summary>
        DMRE_8x64,

        /// <summary>
        ///     Enum value DMRE_8x80
        /// </summary>
        DMRE_8x80,

        /// <summary>
        ///     Enum value DMRE_8x96
        /// </summary>
        DMRE_8x96,

        /// <summary>
        ///     Enum value DMRE_8x120
        /// </summary>
        DMRE_8x120,

        /// <summary>
        ///     Enum value DMRE_8x144
        /// </summary>
        DMRE_8x144,

        /// <summary>
        ///     Enum value DMRE_12x64
        /// </summary>
        DMRE_12x64,

        /// <summary>
        ///     Enum value DMRE_12x88
        /// </summary>
        DMRE_12x88,

        /// <summary>
        ///     Enum value DMRE_16x64
        /// </summary>
        DMRE_16x64,

        /// <summary>
        ///     Enum value DMRE_20x36
        /// </summary>
        DMRE_20x36,

        /// <summary>
        ///     Enum value DMRE_20x44
        /// </summary>
        DMRE_20x44,

        /// <summary>
        ///     Enum value DMRE_20x64
        /// </summary>
        DMRE_20x64,

        /// <summary>
        ///     Enum value DMRE_22x48
        /// </summary>
        DMRE_22x48,

        /// <summary>
        ///     Enum value DMRE_24x48
        /// </summary>
        DMRE_24x48,

        /// <summary>
        ///     Enum value DMRE_24x64
        /// </summary>
        DMRE_24x64,

        /// <summary>
        ///     Enum value DMRE_26x40
        /// </summary>
        DMRE_26x40,

        /// <summary>
        ///     Enum value DMRE_26x48
        /// </summary>
        DMRE_26x48,

        /// <summary>
        ///     Enum value DMRE_26x64
        /// </summary>
        DMRE_26x64

    }
}
