// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="ECIEncodings.cs">
//   Copyright (c) 2021 Aspose.BarCode for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Aspose.BarCode.Cloud.Sdk.Model
{

    /// <summary>
    ///
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ECIEncodings
    {
        /// <summary>
        ///     Enum value NONE
        /// </summary>
        NONE,

        /// <summary>
        ///     Enum value ISO_8859_1
        /// </summary>
        ISO_8859_1,

        /// <summary>
        ///     Enum value ISO_8859_2
        /// </summary>
        ISO_8859_2,

        /// <summary>
        ///     Enum value ISO_8859_3
        /// </summary>
        ISO_8859_3,

        /// <summary>
        ///     Enum value ISO_8859_4
        /// </summary>
        ISO_8859_4,

        /// <summary>
        ///     Enum value ISO_8859_5
        /// </summary>
        ISO_8859_5,

        /// <summary>
        ///     Enum value ISO_8859_6
        /// </summary>
        ISO_8859_6,

        /// <summary>
        ///     Enum value ISO_8859_7
        /// </summary>
        ISO_8859_7,

        /// <summary>
        ///     Enum value ISO_8859_8
        /// </summary>
        ISO_8859_8,

        /// <summary>
        ///     Enum value ISO_8859_9
        /// </summary>
        ISO_8859_9,

        /// <summary>
        ///     Enum value ISO_8859_10
        /// </summary>
        ISO_8859_10,

        /// <summary>
        ///     Enum value ISO_8859_11
        /// </summary>
        ISO_8859_11,

        /// <summary>
        ///     Enum value ISO_8859_13
        /// </summary>
        ISO_8859_13,

        /// <summary>
        ///     Enum value ISO_8859_14
        /// </summary>
        ISO_8859_14,

        /// <summary>
        ///     Enum value ISO_8859_15
        /// </summary>
        ISO_8859_15,

        /// <summary>
        ///     Enum value ISO_8859_16
        /// </summary>
        ISO_8859_16,

        /// <summary>
        ///     Enum value Shift_JIS
        /// </summary>
        Shift_JIS,

        /// <summary>
        ///     Enum value Win1250
        /// </summary>
        Win1250,

        /// <summary>
        ///     Enum value Win1251
        /// </summary>
        Win1251,

        /// <summary>
        ///     Enum value Win1252
        /// </summary>
        Win1252,

        /// <summary>
        ///     Enum value Win1256
        /// </summary>
        Win1256,

        /// <summary>
        ///     Enum value UTF16BE
        /// </summary>
        UTF16BE,

        /// <summary>
        ///     Enum value UTF8
        /// </summary>
        UTF8,

        /// <summary>
        ///     Enum value US_ASCII
        /// </summary>
        US_ASCII,

        /// <summary>
        ///     Enum value Big5
        /// </summary>
        Big5,

        /// <summary>
        ///     Enum value GB18030
        /// </summary>
        GB18030,

        /// <summary>
        ///     Enum value EUC_KR
        /// </summary>
        EUC_KR

    }
}
