// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="QrParams.cs">
//   Copyright (c) 2020 Aspose.BarCode for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

using System;
using System.Collections.Generic;
using System.Text;

namespace Aspose.BarCode.Cloud.Sdk.Model
{

    /// <summary>
    ///     QR parameters.
    /// </summary>
    public class QrParams
    {
        /// <summary>
        ///     QR / MicroQR selector mode. Select ForceQR for standard QR symbols, Auto for MicroQR.
        /// </summary>
        public QREncodeType? EncodeType { get; set; }

        /// <summary>
        ///     Extended Channel Interpretation Identifiers. It is used to tell the barcode reader details about the used references for encoding the data in the symbol. Current implementation consists all well known charset encodings.
        /// </summary>
        public ECIEncodings? ECIEncoding { get; set; }

        /// <summary>
        ///     QR symbology type of BarCode&#39;s encoding mode. Default value: QREncodeMode.Auto.
        /// </summary>
        public QREncodeMode? EncodeMode { get; set; }

        /// <summary>
        ///     Level of Reed-Solomon error correction for QR barcode. From low to high: LevelL, LevelM, LevelQ, LevelH. see QRErrorLevel.
        /// </summary>
        public QRErrorLevel? ErrorLevel { get; set; }

        /// <summary>
        ///     Version of QR Code. From Version1 to Version40 for QR code and from M1 to M4 for MicroQr. Default value is QRVersion.Auto.
        /// </summary>
        public QRVersion? Version { get; set; }

        /// <summary>
        ///     Height/Width ratio of 2D BarCode module.
        /// </summary>
        public double? AspectRatio { get; set; }

        /// <summary>
        ///     Encoding of codetext.
        /// </summary>
        public string TextEncoding { get; set; }

        /// <summary>
        ///     QR structured append parameters.
        /// </summary>
        public StructuredAppend StructuredAppend { get; set; }

        /// <summary>
        ///     Get the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QrParams {\n");
            sb.Append("  AspectRatio: ").Append(AspectRatio).Append("\n");
            sb.Append("  TextEncoding: ").Append(TextEncoding).Append("\n");
            sb.Append("  EncodeType: ").Append(EncodeType).Append("\n");
            sb.Append("  ECIEncoding: ").Append(ECIEncoding).Append("\n");
            sb.Append("  EncodeMode: ").Append(EncodeMode).Append("\n");
            sb.Append("  ErrorLevel: ").Append(ErrorLevel).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  StructuredAppend: ").Append(StructuredAppend).Append("\n");
            sb.Append("}\n");

            return sb.ToString();
        }
    }
}
