// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="QRVersion.cs">
//   Copyright (c) 2021 Aspose.BarCode for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Aspose.BarCode.Cloud.Sdk.Model
{

    /// <summary>
    ///
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum QRVersion
    {
        /// <summary>
        ///     Enum value Auto
        /// </summary>
        Auto,

        /// <summary>
        ///     Enum value Version01
        /// </summary>
        Version01,

        /// <summary>
        ///     Enum value Version02
        /// </summary>
        Version02,

        /// <summary>
        ///     Enum value Version03
        /// </summary>
        Version03,

        /// <summary>
        ///     Enum value Version04
        /// </summary>
        Version04,

        /// <summary>
        ///     Enum value Version05
        /// </summary>
        Version05,

        /// <summary>
        ///     Enum value Version06
        /// </summary>
        Version06,

        /// <summary>
        ///     Enum value Version07
        /// </summary>
        Version07,

        /// <summary>
        ///     Enum value Version08
        /// </summary>
        Version08,

        /// <summary>
        ///     Enum value Version09
        /// </summary>
        Version09,

        /// <summary>
        ///     Enum value Version10
        /// </summary>
        Version10,

        /// <summary>
        ///     Enum value Version11
        /// </summary>
        Version11,

        /// <summary>
        ///     Enum value Version12
        /// </summary>
        Version12,

        /// <summary>
        ///     Enum value Version13
        /// </summary>
        Version13,

        /// <summary>
        ///     Enum value Version14
        /// </summary>
        Version14,

        /// <summary>
        ///     Enum value Version15
        /// </summary>
        Version15,

        /// <summary>
        ///     Enum value Version16
        /// </summary>
        Version16,

        /// <summary>
        ///     Enum value Version17
        /// </summary>
        Version17,

        /// <summary>
        ///     Enum value Version18
        /// </summary>
        Version18,

        /// <summary>
        ///     Enum value Version19
        /// </summary>
        Version19,

        /// <summary>
        ///     Enum value Version20
        /// </summary>
        Version20,

        /// <summary>
        ///     Enum value Version21
        /// </summary>
        Version21,

        /// <summary>
        ///     Enum value Version22
        /// </summary>
        Version22,

        /// <summary>
        ///     Enum value Version23
        /// </summary>
        Version23,

        /// <summary>
        ///     Enum value Version24
        /// </summary>
        Version24,

        /// <summary>
        ///     Enum value Version25
        /// </summary>
        Version25,

        /// <summary>
        ///     Enum value Version26
        /// </summary>
        Version26,

        /// <summary>
        ///     Enum value Version27
        /// </summary>
        Version27,

        /// <summary>
        ///     Enum value Version28
        /// </summary>
        Version28,

        /// <summary>
        ///     Enum value Version29
        /// </summary>
        Version29,

        /// <summary>
        ///     Enum value Version30
        /// </summary>
        Version30,

        /// <summary>
        ///     Enum value Version31
        /// </summary>
        Version31,

        /// <summary>
        ///     Enum value Version32
        /// </summary>
        Version32,

        /// <summary>
        ///     Enum value Version33
        /// </summary>
        Version33,

        /// <summary>
        ///     Enum value Version34
        /// </summary>
        Version34,

        /// <summary>
        ///     Enum value Version35
        /// </summary>
        Version35,

        /// <summary>
        ///     Enum value Version36
        /// </summary>
        Version36,

        /// <summary>
        ///     Enum value Version37
        /// </summary>
        Version37,

        /// <summary>
        ///     Enum value Version38
        /// </summary>
        Version38,

        /// <summary>
        ///     Enum value Version39
        /// </summary>
        Version39,

        /// <summary>
        ///     Enum value Version40
        /// </summary>
        Version40,

        /// <summary>
        ///     Enum value VersionM1
        /// </summary>
        VersionM1,

        /// <summary>
        ///     Enum value VersionM2
        /// </summary>
        VersionM2,

        /// <summary>
        ///     Enum value VersionM3
        /// </summary>
        VersionM3,

        /// <summary>
        ///     Enum value VersionM4
        /// </summary>
        VersionM4

    }
}
