name: Build examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-examples:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup latest version of dotnet
      uses: actions/setup-dotnet@v3
    - name: Build nuget with latest version
      run: ./scripts/pack-nuget.bash "examples/nuget-packages"
    - name: Build examples with new nuget
      run: dotnet build --warnaserror "examples/examples.sln"
