name: .NET Core Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core
        # For versions
        include:
          - dotnet-version: 3.1.x
            framework: netcoreapp3.1
          - dotnet-version: 6.0.x
            framework: net6.0
          - dotnet-version: 7.0.x
            framework: net7.0

    continue-on-error: true

    steps:
    - uses: actions/checkout@v3
    - name: Setup latest version of dotnet
      uses: actions/setup-dotnet@v3
    - name: Build with latest version
      run: dotnet build

    - name: Setup ${{ matrix.dotnet-version }} version of dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Test with ${{ matrix.dotnet-version }}
      run: dotnet test --no-build --verbosity normal --framework ${{ matrix.framework }}
      env:
        TEST_CONFIGURATION_JWT_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}

  docker-build:
    needs: [ build-and-test ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile
