name: .NET Framework Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Build the Solution
      run: msbuild -restore -p:Configuration=Release

    - name: Test with VSTest
      run: VSTest.Console.exe /Framework:".NETFramework,Version=v4.6.1" Tests\bin\Release\net461\Aspose.BarCode.Cloud.Sdk.Tests.dll
      env:
        TEST_CONFIGURATION_JWT_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}

    - name: Build NuGet package
      run: cmd scripts\build_package.cmd
