name: Pack into Nuget package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pack-nuget:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile
